### ISSUE TITLE
Conditional save or modify

### ISSUE THREAD

**Issue by mike-schenk** [robconery/dox#4]
I would love to see dox provide the ability to detect and prevent lost "concurrent" updates. By which I mean concurrent users who retrieve a document in one transaction, then modify it outside the DB and save it back in another transaction.

Maybe dox could keep a version number on each document that increments on every save/modify. The version number could be returned with results. `Save` and `modify` could be made to optionally compare the current version number with the one specified in the incoming document and return an error if they don't match.

**Comment by robconery** [comment]
Sounds like you're asking for custom dirty read/write? Right now the MVCC will help out with this, but you'll get a delay with the update. So if I pull user 1 and you pull user 1 and we both issue a write, the MVCC will be used for the first write, the second will be queued.

Is this what you're asking for? Outside of that, I have no interest in going around concurrency in PostgreSQL because no matter what I do, PostgreSQL will do it better.
